### ISSUE TITLE
Missing WIFI_CONFIG

### ISSUE THREAD

**Issue by davidpcahill** [pimoroni/unicorn#2]
There's a missing file in this repository. It's supposed to be in the common examples folder called wifi_config.py I believe?

**Comment by TagWolf** [comment]
Resolved, formatting of file is:
WIFI_CONFIG.py
```
SSID = "myssid"
PSK = "wifi password"
COUNTRY = "US"  # Change to your local two-letter ISO 3166-1 country code
```

also to note, you may need network_manager.py as well.

Both examples are here:
https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/common
